"""Core data models for Cryplative.

All models are Pydantic v2 BaseModel classes. They are the single source
of truth for data shapes in the system.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, field_validator, model_validator


class Candle(BaseModel):
    """A single OHLCV candle."""

    symbol: str  # e.g., "BTC/USDT" (ccxt unified format)
    interval: str  # e.g., "1h", "4h", "1d"
    open_time: int  # Unix timestamp (ms)
    open: float
    high: float
    low: float
    close: float
    volume: float
    close_time: int  # Unix timestamp (ms)
    closed: bool  # False if candle is still forming

    @field_validator("open", "high", "low", "close", "volume")
    @classmethod
    def non_negative_price_volume(cls, v: float) -> float:
        if v < 0:
            raise ValueError("Value must be non-negative")
        return v

    @model_validator(mode="after")
    def open_before_close(self) -> Candle:
        if self.open_time >= self.close_time:
            raise ValueError("open_time must be less than close_time")
        return self


class SignalDirection(str, Enum):
    """Direction of a trading signal."""

    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    """Type of order to place."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"


class Signal(BaseModel):
    """A trading signal generated by a strategy."""

    strategy_id: str
    symbol: str
    timestamp: int  # Unix timestamp (ms)
    direction: SignalDirection
    order_type: OrderType
    price: float | None  # Required for LIMIT orders
    quantity: float
    stop_loss: float | None
    take_profit: float | None
    confidence: float  # 0.0 - 1.0
    metadata: dict[str, Any] = {}

    @field_validator("confidence")
    @classmethod
    def confidence_range(cls, v: float) -> float:
        if not 0.0 <= v <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")
        return v

    @field_validator("quantity")
    @classmethod
    def non_negative_quantity(cls, v: float) -> float:
        if v < 0:
            raise ValueError("quantity must be non-negative")
        return v

    @model_validator(mode="after")
    def limit_order_requires_price(self) -> Signal:
        if self.order_type == OrderType.LIMIT and self.price is None:
            raise ValueError("price is required for LIMIT orders")
        return self


class TradeStatus(str, Enum):
    """Status of a trade."""

    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class RunContext(str, Enum):
    """Context in which a strategy is running."""

    BACKTEST = "BACKTEST"
    PAPER = "PAPER"
    REAL = "REAL"


class Trade(BaseModel):
    """A single trade (opened and optionally closed)."""

    trade_id: str  # UUID
    signal: Signal
    entry_price: float
    exit_price: float | None  # None if still open
    quantity: float
    pnl: float | None  # None if still open
    pnl_percentage: float | None
    status: TradeStatus
    opened_at: int  # Unix timestamp (ms)
    closed_at: int | None
    context: RunContext

    @field_validator("entry_price", "quantity")
    @classmethod
    def non_negative_trade_fields(cls, v: float) -> float:
        if v < 0:
            raise ValueError("Value must be non-negative")
        return v


class StrategyConfig(BaseModel):
    """Configuration for a strategy instance."""

    strategy_id: str
    strategy_name: str
    version: str
    symbol: str
    interval: str
    parameters: dict[str, Any] = {}
    state: dict[str, Any] = {}  # Persistent state across runs


class StrategyMetrics(BaseModel):
    """Performance metrics from a strategy run."""

    total_return: float
    sharpe_ratio: float
    max_drawdown: float
    win_rate: float
    total_trades: int
    profit_factor: float


class StrategyResult(BaseModel):
    """Complete result of a strategy run (backtest, paper, or real)."""

    strategy_id: str
    run_type: RunContext
    start_date: str  # ISO 8601
    end_date: str  # ISO 8601
    parameters: dict[str, Any]
    trades: list[Trade]
    metrics: StrategyMetrics
    created_at: str  # ISO 8601
